safe: false
url: http://wiesbaden.freifunk.net
baseurl: /
lang: de

community:
  # Metadata
  name: "Wiesbaden"
  meta: "Freifunk MWU"
  country: "DE"

  # SSID
  ssid: "wiesbaden.freifunk.net"

  # Custom URLs
  url_wiki:  "https://wiki.freifunk-mwu.de"
  url_calendar:  "/ffwi-calendar.ics"
  url_meshviewer: "https://map.wiesbaden.freifunk.net"
  url_mailman: "http://lists.freifunk.net/mailman/listinfo/wiesbaden-freifunk.net"
  url_git: "http://github.com/freifunk-mwu"

  # Mail Contacts
  mail_info: "info@freifunk-wiesbaden.de"
  mail_keys: "keys@freifunk-wiesbaden.de"
  mail_discussion: "wiesbaden@freifunk.net"

  # Other Contacts
  #sip: ["space@sip.ffgc", "space@10.35.0.1"] # Optional
  twitter: "freifunkwi" # Optional
  irc: "ircs://irc.hackint.net/ffmwu"
  irc_web: "https://webirc.hackint.org/#irc://irc.hackint.org/#hackint"
  facebook: "FreifunkWiesbaden"
  telegram: "freifunkwiesbaden"

  # GPS
  geo_lat: 50.08
  geo_lon: 8.22

  # Donations
  donation_iban: "DE41551900000654997014"
  donation_bic: "MVBMDE55XXX"

firmware:
  base: "https://firmware.wiesbaden.freifunk.net/stable/"
  version: "2017.1.8+mwu1"
  major_version: "2017.1.8"
  minor_version: "mwu1"
  prefix: "gluon-ffwi"
  type: "gluon"

  # URL to the site repo (gitweb,github...)
  gluon_site: "https://github.com/freifunk-mwu/sites-ffmwu"
  # Path to local checkout of the site repo
  gluon_site_dir: "../gluon/site"

tld:
  label: "ffwi.org"
  ns:
    - "10.56.0.7"
    - "fd56:b4dc:4b1e::a38:7"
    - "10.56.0.23"
    - "fd56:b4dc:4b1e::a38:17"
    - "10.56.0.36"
    - "fd56:b4dc:4b1e::a38:e7"
    - "10.56.0.208"
    - "fd56:b4dc:4b1e::a38:d0"

collections:
  events:
    output: true
    permalink: /event/:path/
  pressemitteilungen:
    output: true
    permalink: /pressemitteilung/:path/

# Config for feed.xml, customized version of https://github.com/snaptortoise/jekyll-rss-feeds
feed:
  name: Freifunk Wiesbaden
  description: Blog der Wiesbadener Freifunk-Community
