safe: false
url: http://testpage.freifunk-wiesbaden.de/

community:
  # Metadata
  name: "Wiesbaden"
  meta: "Freifunk MWU"
  country: "DE"

  # SSID
  ssid: "wiesbaden.freifunk.net"

  # Custom URLs
  url_wiki:  "http://wiki.freifunk-mainz.de"
  url_blog:  "http://blog.freifunk-wiesbaden.de"
  url_calendar:  "http://blog.freifunk-wiesbaden.de/termine"
  url_geomap: "http://gluonmap.freifunk-wiesbaden.de/geomap.html"
  url_graph: "http://gluonmap.freifunk-wiesbaden.de/graph.html"
  url_nodelist: "http://gluonmap.freifunk-wiesbaden.de/list.html"
  url_mailman: "http://lists.freifunk.net/mailman/listinfo/wiesbaden-freifunk.net"
  url_git: "http://github.com/freifunk-mwu"

  # Mail Contacts
  mail_info: "info@freifunk-wiesbaden.de"
  mail_keys: "keys@freifunk-wiesbaden.de"
  mail_discussion: "wiesbaden@freifunk.net"

  # Other Contacts
  #sip: ["space@sip.ffgc", "space@10.35.0.1"] # Optional
  twitter: "freifunkwi" # Optional
  irc: "ircs://irc.hackint.net/ffmwu"

  # GPS
  geo_lat: 50.08
  geo_lon: 8.22

firmware:
  base: "http://firmware.freifunk-wiesbaden.de/stable/"
  type: "gluon"

  # URL to the site repo (gitweb,github...)
  gluon_site: "https://github.com/freifunk-mwu/site-ffmwu"
  # Path to local checkout of the site repo
  gluon_site_dir: "../gluon/site"

tld:
  label: "ffwi.org"
  ns:
    - "10.56.0.5"
    - "fd56:b4dc:4b1e::a38:5"
    - "10.56.0.7"
    - "fd56:b4dc:4b1e::a38:7"
    - "10.56.0.23"
    - "fd56:b4dc:4b1e::a38:17"
