safe: false
url: http://wiesbaden.freifunk.net
baseurl: /

community:
  # Metadata
  name: "Wiesbaden"
  meta: "Freifunk MWU"
  country: "DE"

  # SSID
  ssid: "wiesbaden.freifunk.net"

  # Custom URLs
  url_wiki:  "http://wiki.freifunk-mainz.de"
  url_calendar:  "http://wiesbaden.freifunk.net/ffwi-calendar.ics"
  url_meshviewer: "http://map.wiesbaden.freifunk.net"
  url_mailman: "http://lists.freifunk.net/mailman/listinfo/wiesbaden-freifunk.net"
  url_git: "http://github.com/freifunk-mwu"

  # Mail Contacts
  mail_info: "info@freifunk-wiesbaden.de"
  mail_keys: "keys@freifunk-wiesbaden.de"
  mail_discussion: "wiesbaden@freifunk.net"

  # Other Contacts
  #sip: ["space@sip.ffgc", "space@10.35.0.1"] # Optional
  twitter: "freifunkwi" # Optional
  irc: "ircs://irc.hackint.net/ffmwu"
  irc_web: "https://kiwiirc.com/client/irc.hackint.net/#ffmwu"
  facebook: "FreifunkWiesbaden"

  # GPS
  geo_lat: 50.08
  geo_lon: 8.22

  # Donations
  donation_iban: "DE41551900000654997014"
  donation_bic: "MVBMDE55XXX"

firmware:
  base: "http://firmware.wiesbaden.freifunk.net/stable/"
  version: "0.2.2-stable"
  prefix: "gluon-ffwi"
  type: "gluon"

  # URL to the site repo (gitweb,github...)
  gluon_site: "https://github.com/freifunk-mwu/site-ffmwu"
  # Path to local checkout of the site repo
  gluon_site_dir: "../gluon/site"

tld:
  label: "ffwi.org"
  ns:
    - "10.56.0.7"
    - "fd56:b4dc:4b1e::a38:7"
    - "10.56.0.23"
    - "fd56:b4dc:4b1e::a38:17"
    - "10.56.0.36"
    - "fd56:b4dc:4b1e::a38:e7"
    - "10.56.0.208"
    - "fd56:b4dc:4b1e::a38:d0"


collections:
  events:
    output: true
    permalink: /event/:path/

# Config for feed.xml, customized version of https://github.com/snaptortoise/jekyll-rss-feeds
feed:
  name: Freifunk Wiesbaden
  description: Blog der Wiesbadener Freifunk-Community
